# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-29 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_feedback_api', '0003_auto_20170129_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='metadata_json',
            field=models.TextField(blank=True, null=True, verbose_name=b'json encoded string with metadata'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='responded_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name=b'date created'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='response',
            field=models.TextField(blank=True, db_index=True, null=True, verbose_name=b'the response from the tasker'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='shown_to_tasker_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name=b'date created'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='tasker_slack_name',
            field=models.TextField(blank=True, db_index=True, null=True, verbose_name=b'The slack name of the tasker (without the @)'),
        ),
    ]
