# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-29 04:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_feedback_api', '0004_auto_20170129_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='media_path_1',
            field=models.TextField(db_index=True, verbose_name=b'media path #1 (relative to /mnt/efs/human-feedback/media/ )'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='media_path_2',
            field=models.TextField(db_index=True, verbose_name=b'media path #2 (relative to /mnt/efs/human-feedback/media/ )'),
        ),
    ]
