# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-10 23:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('human_feedback_api', '0005_auto_20170129_0459'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Greeting',
        ),
    ]
