# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-10 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_feedback_api', '0006_delete_greeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='priority',
            field=models.FloatField(db_index=True, default=0, verbose_name=b'site will display higher priority items first'),
            preserve_default=False,
        ),
    ]
