# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-12 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_feedback_api', '0009_feedback_experiment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='canceled_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name=b'time processed and canceled by labeler'),
        ),
    ]
