# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-02 17:30
from __future__ import unicode_literals

from django.db import migrations, models
import human_feedback_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('human_feedback_api', '0010_add_canceled_at_to_feedbacks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='canceled_at',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='metadata_json',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='tasker_slack_name',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='experiment_name',
            field=models.TextField(blank=True, null=True, verbose_name='name of experiment'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='media_path_1',
            field=models.TextField(db_index=True, verbose_name='media path #1 (relative to /mnt/efs/human-feedback/media/ )'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='media_path_2',
            field=models.TextField(db_index=True, verbose_name='media path #2 (relative to /mnt/efs/human-feedback/media/ )'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='note',
            field=models.TextField(blank=True, default='', verbose_name='note to be displayed along with the query'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='priority',
            field=models.FloatField(db_index=True, verbose_name='site will display higher priority items first'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='responded_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='time response received'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='response',
            field=models.TextField(blank=True, db_index=True, null=True, verbose_name='the response from the tasker'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='response_kind',
            field=models.TextField(db_index=True, validators=[human_feedback_api.models.validate_inclusion_of_response_kind], verbose_name='the response from the tasker'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='shown_to_tasker_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='time shown to tasker'),
        ),
    ]
