# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-02 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_feedback_api', '0011_remove_unused_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='experiment_name',
            field=models.TextField(verbose_name='name of experiment'),
        ),
    ]
