# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-02 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_feedback_api', '0012_Require experiment_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='media_path_1',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='media_path_2',
        ),
        migrations.AddField(
            model_name='feedback',
            name='media_url_1',
            field=models.TextField(db_index=True, default=1, verbose_name='media url #1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='media_url_2',
            field=models.TextField(db_index=True, default=1, verbose_name='media url #2'),
            preserve_default=False,
        ),
    ]
