# Generated by Django 4.1.3 on 2022-12-29 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_feedback_api', '0014_feedback_to_comparison'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparison',
            name='local',
            field=models.BooleanField(default=False),
        ),
    ]
